apiVersion: opg.ewbi.nby.one/v1beta1
kind: ApplicationInstance
metadata:
  namespace: katalis-dev-guest
  labels:
    opg.ewbi.nby.one/federation-context-id: dc81e752-d230-5c7e-9bb1-e8cc4b59f828 # get this from Guest Federation's status
    opg.ewbi.nby.one/federation-relation: "guest"
    opg.ewbi.nby.one/federation-callback-id: 5tyde22c-d245-480d-b01e-24e38e7689de
    opg.ewbi.nby.one/id: app-inst-rest
  name: app-inst-rest
spec:
  appId: app-rest
  appProviderId: nearbycomputing
  appVersion: 1.23.3
  zoneInfo:
    flavourId: NOT_SPECIFIED
    resPool: mock-res-pool
    resourceConsumption: RESERVED_RES_AVOID
    zoneId: "zone-es-madrid-001"
