# Create this when the Origin Partner (Client)
# credentials are created in the host system
apiVersion: opg.ewbi.katalis.com/v1beta1
kind: Federation
metadata:
  namespace: katalis-dev-host
  annotations:
    opg.ewbi.katalis.com/origin-mcc: "001" # not used, will be overridden by /partner request body
    opg.ewbi.katalis.com/origin-mncs: "001" # not used, will be overridden by /partner request body
  labels:
    opg.ewbi.katalis.com/federation-relation: host
    # opg.ewbi.katalis.com/host-operator-org-id: "
    opg.ewbi.katalis.com/origin-operator-name: guestName
    opg.ewbi.katalis.com/origin-client-id: 3acde22c-d245-480d-b01e-24e38e01806e # uuid, will match with clientID request
    opg.ewbi.katalis.com/origin-country-code: ES
    opg.ewbi.katalis.com/federation-technology: rest
  name: fed-host-rest # prefix-uuid
spec:
  offeredAvailabilityZones:
    - geographyDetails: "Milano, Italia. Area urbana a forte densità di traffico e industriale."
      geolocation: "45.4642,9.1900"
      zoneId: "2a8fffaf-50de-4f93-8c6f-05f1c84b5a5f"
    - geographyDetails: "Roma, Italia. Area periferica residenziale, bassa densità di popolazione."
      geolocation: "41.9028,12.4964"
      zoneId: "3a8fffaf-50de-4f93-8c6f-05f1c84b5a5f"
    - geographyDetails: "Torino, Italia. Zona rurale vicino al confine con la Francia."
      geolocation: "45.0703,7.6869"
      zoneId: "4a8fffaf-50de-4f93-8c6f-05f1c84b5a5f"
  guestPartnerCredentials:
    clientId:   3acde22c-d245-480d-b01e-24e38e01806e # uuid
