apiVersion: opg.ewbi.katalis.com/v1beta1
kind: Image
metadata:
  namespace: guest
  name: file-k
spec:
  appProviderId: nearbycomputing
  fileName: "nginx:latest"
  fileType: DOCKER
  fileVersion: "latest"
  image:
    instructionSetArchitecture: ISA_X86_64
    os:
      architecture: x86_64
      distribution: UBUNTU
      license: OS_LICENSE_TYPE_FREE
      version: OS_VERSION_UBUNTU_2204_LTS
  repoLocation:
    password: repoPass
    token: repoAccessToken
    type: public
    url: "docker.io"
    username: repoUser