//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPointInfo) DeepCopyInto(out *AccessPointInfo) {
	*out = *in
	in.AccessPoints.DeepCopyInto(&out.AccessPoints)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPointInfo.
func (in *AccessPointInfo) DeepCopy() *AccessPointInfo {
	if in == nil {
		return nil
	}
	out := new(AccessPointInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPoints) DeepCopyInto(out *AccessPoints) {
	*out = *in
	if in.Ipv4Addresses != nil {
		in, out := &in.Ipv4Addresses, &out.Ipv4Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ipv6Addresses != nil {
		in, out := &in.Ipv6Addresses, &out.Ipv6Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPoints.
func (in *AccessPoints) DeepCopy() *AccessPoints {
	if in == nil {
		return nil
	}
	out := new(AccessPoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlarmStatus) DeepCopyInto(out *AlarmStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlarmStatus.
func (in *AlarmStatus) DeepCopy() *AlarmStatus {
	if in == nil {
		return nil
	}
	out := new(AlarmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppIdList) DeepCopyInto(out *AppIdList) {
	*out = *in
	if in.ZoneIds != nil {
		in, out := &in.ZoneIds, &out.ZoneIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppIdList.
func (in *AppIdList) DeepCopy() *AppIdList {
	if in == nil {
		return nil
	}
	out := new(AppIdList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppMetaData) DeepCopyInto(out *AppMetaData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppMetaData.
func (in *AppMetaData) DeepCopy() *AppMetaData {
	if in == nil {
		return nil
	}
	out := new(AppMetaData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Application) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationInstance) DeepCopyInto(out *ApplicationInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationInstance.
func (in *ApplicationInstance) DeepCopy() *ApplicationInstance {
	if in == nil {
		return nil
	}
	out := new(ApplicationInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationInstanceList) DeepCopyInto(out *ApplicationInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationInstanceList.
func (in *ApplicationInstanceList) DeepCopy() *ApplicationInstanceList {
	if in == nil {
		return nil
	}
	out := new(ApplicationInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationInstanceSpec) DeepCopyInto(out *ApplicationInstanceSpec) {
	*out = *in
	out.ZoneInfo = in.ZoneInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationInstanceSpec.
func (in *ApplicationInstanceSpec) DeepCopy() *ApplicationInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationInstanceStatus) DeepCopyInto(out *ApplicationInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AccessPointInfo != nil {
		in, out := &in.AccessPointInfo, &out.AccessPointInfo
		*out = make([]AccessPointInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationInstanceStatus.
func (in *ApplicationInstanceStatus) DeepCopy() *ApplicationInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationList) DeepCopyInto(out *ApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Application, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationList.
func (in *ApplicationList) DeepCopy() *ApplicationList {
	if in == nil {
		return nil
	}
	out := new(ApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSpec) DeepCopyInto(out *ApplicationSpec) {
	*out = *in
	if in.ComponentSpecs != nil {
		in, out := &in.ComponentSpecs, &out.ComponentSpecs
		*out = make([]ComponentSpecRef, len(*in))
		copy(*out, *in)
	}
	out.MetaData = in.MetaData
	out.QoSProfile = in.QoSProfile
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSpec.
func (in *ApplicationSpec) DeepCopy() *ApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStatus) DeepCopyInto(out *ApplicationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStatus.
func (in *ApplicationStatus) DeepCopy() *ApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Artefact) DeepCopyInto(out *Artefact) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Artefact.
func (in *Artefact) DeepCopy() *Artefact {
	if in == nil {
		return nil
	}
	out := new(Artefact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Artefact) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtefactList) DeepCopyInto(out *ArtefactList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Artefact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtefactList.
func (in *ArtefactList) DeepCopy() *ArtefactList {
	if in == nil {
		return nil
	}
	out := new(ArtefactList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtefactList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtefactSpec) DeepCopyInto(out *ArtefactSpec) {
	*out = *in
	if in.ComponentSpec != nil {
		in, out := &in.ComponentSpec, &out.ComponentSpec
		*out = make([]ComponentSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtefactSpec.
func (in *ArtefactSpec) DeepCopy() *ArtefactSpec {
	if in == nil {
		return nil
	}
	out := new(ArtefactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtefactStatus) DeepCopyInto(out *ArtefactStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtefactStatus.
func (in *ArtefactStatus) DeepCopy() *ArtefactStatus {
	if in == nil {
		return nil
	}
	out := new(ArtefactStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssocPolicy) DeepCopyInto(out *AssocPolicy) {
	*out = *in
	in.AppIdList.DeepCopyInto(&out.AppIdList)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssocPolicy.
func (in *AssocPolicy) DeepCopy() *AssocPolicy {
	if in == nil {
		return nil
	}
	out := new(AssocPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityZone) DeepCopyInto(out *AvailabilityZone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityZone.
func (in *AvailabilityZone) DeepCopy() *AvailabilityZone {
	if in == nil {
		return nil
	}
	out := new(AvailabilityZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvailabilityZone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityZoneList) DeepCopyInto(out *AvailabilityZoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AvailabilityZone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityZoneList.
func (in *AvailabilityZoneList) DeepCopy() *AvailabilityZoneList {
	if in == nil {
		return nil
	}
	out := new(AvailabilityZoneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvailabilityZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityZoneSpec) DeepCopyInto(out *AvailabilityZoneSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityZoneSpec.
func (in *AvailabilityZoneSpec) DeepCopy() *AvailabilityZoneSpec {
	if in == nil {
		return nil
	}
	out := new(AvailabilityZoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityZoneStatus) DeepCopyInto(out *AvailabilityZoneStatus) {
	*out = *in
	if in.FlavoursSupported != nil {
		in, out := &in.FlavoursSupported, &out.FlavoursSupported
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityZoneStatus.
func (in *AvailabilityZoneStatus) DeepCopy() *AvailabilityZoneStatus {
	if in == nil {
		return nil
	}
	out := new(AvailabilityZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Caps) DeepCopyInto(out *Caps) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Caps.
func (in *Caps) DeepCopy() *Caps {
	if in == nil {
		return nil
	}
	out := new(Caps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommandLine) DeepCopyInto(out *CommandLine) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommandLine.
func (in *CommandLine) DeepCopy() *CommandLine {
	if in == nil {
		return nil
	}
	out := new(CommandLine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentSpec) DeepCopyInto(out *ComponentSpec) {
	*out = *in
	in.CommandLineParams.DeepCopyInto(&out.CommandLineParams)
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ComputeResourceProfile = in.ComputeResourceProfile
	if in.ExposedInterfaces != nil {
		in, out := &in.ExposedInterfaces, &out.ExposedInterfaces
		*out = make([]ExposedInterface, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentSpec.
func (in *ComponentSpec) DeepCopy() *ComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentSpecRef) DeepCopyInto(out *ComponentSpecRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentSpecRef.
func (in *ComponentSpecRef) DeepCopy() *ComponentSpecRef {
	if in == nil {
		return nil
	}
	out := new(ComponentSpecRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeResourceProfile) DeepCopyInto(out *ComputeResourceProfile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeResourceProfile.
func (in *ComputeResourceProfile) DeepCopy() *ComputeResourceProfile {
	if in == nil {
		return nil
	}
	out := new(ComputeResourceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Credentials) DeepCopyInto(out *Credentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Credentials.
func (in *Credentials) DeepCopy() *Credentials {
	if in == nil {
		return nil
	}
	out := new(Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposedInterface) DeepCopyInto(out *ExposedInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposedInterface.
func (in *ExposedInterface) DeepCopy() *ExposedInterface {
	if in == nil {
		return nil
	}
	out := new(ExposedInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Federation) DeepCopyInto(out *Federation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Federation.
func (in *Federation) DeepCopy() *Federation {
	if in == nil {
		return nil
	}
	out := new(Federation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Federation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationData) DeepCopyInto(out *FederationData) {
	*out = *in
	if in.PartnerCallbackCredentials != nil {
		in, out := &in.PartnerCallbackCredentials, &out.PartnerCallbackCredentials
		*out = new(Credentials)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationData.
func (in *FederationData) DeepCopy() *FederationData {
	if in == nil {
		return nil
	}
	out := new(FederationData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationHealthInfo) DeepCopyInto(out *FederationHealthInfo) {
	*out = *in
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationHealthInfo.
func (in *FederationHealthInfo) DeepCopy() *FederationHealthInfo {
	if in == nil {
		return nil
	}
	out := new(FederationHealthInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationList) DeepCopyInto(out *FederationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Federation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationList.
func (in *FederationList) DeepCopy() *FederationList {
	if in == nil {
		return nil
	}
	out := new(FederationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FederationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationSpec) DeepCopyInto(out *FederationSpec) {
	*out = *in
	if in.FederationData != nil {
		in, out := &in.FederationData, &out.FederationData
		*out = new(FederationData)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdateData != nil {
		in, out := &in.UpdateData, &out.UpdateData
		*out = new(UpdateData)
		(*in).DeepCopyInto(*out)
	}
	if in.MobileNetworkIds != nil {
		in, out := &in.MobileNetworkIds, &out.MobileNetworkIds
		*out = new(MobileNetworkIds)
		(*in).DeepCopyInto(*out)
	}
	if in.FixedNetworkIds != nil {
		in, out := &in.FixedNetworkIds, &out.FixedNetworkIds
		*out = make([]FixedNetworkId, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationSpec.
func (in *FederationSpec) DeepCopy() *FederationSpec {
	if in == nil {
		return nil
	}
	out := new(FederationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationStatus) DeepCopyInto(out *FederationStatus) {
	*out = *in
	if in.ServiceEndpoint != nil {
		in, out := &in.ServiceEndpoint, &out.ServiceEndpoint
		*out = new(ServiceEndpoint)
		(*in).DeepCopyInto(*out)
	}
	if in.MobileNetworkIds != nil {
		in, out := &in.MobileNetworkIds, &out.MobileNetworkIds
		*out = new(MobileNetworkIds)
		(*in).DeepCopyInto(*out)
	}
	if in.FixedNetworkIds != nil {
		in, out := &in.FixedNetworkIds, &out.FixedNetworkIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ZoneDetails != nil {
		in, out := &in.ZoneDetails, &out.ZoneDetails
		*out = make([]ZoneDetail, len(*in))
		copy(*out, *in)
	}
	if in.PlatformCaps != nil {
		in, out := &in.PlatformCaps, &out.PlatformCaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FederationHealthInfo != nil {
		in, out := &in.FederationHealthInfo, &out.FederationHealthInfo
		*out = new(FederationHealthInfo)
		**out = **in
	}
	if in.Caps != nil {
		in, out := &in.Caps, &out.Caps
		*out = new(Caps)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationStatus.
func (in *FederationStatus) DeepCopy() *FederationStatus {
	if in == nil {
		return nil
	}
	out := new(FederationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *File) DeepCopyInto(out *File) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new File.
func (in *File) DeepCopy() *File {
	if in == nil {
		return nil
	}
	out := new(File)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *File) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileList) DeepCopyInto(out *FileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]File, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileList.
func (in *FileList) DeepCopy() *FileList {
	if in == nil {
		return nil
	}
	out := new(FileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSpec) DeepCopyInto(out *FileSpec) {
	*out = *in
	out.Repo = in.Repo
	out.Image = in.Image
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSpec.
func (in *FileSpec) DeepCopy() *FileSpec {
	if in == nil {
		return nil
	}
	out := new(FileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileStatus) DeepCopyInto(out *FileStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileStatus.
func (in *FileStatus) DeepCopy() *FileStatus {
	if in == nil {
		return nil
	}
	out := new(FileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Image) DeepCopyInto(out *Image) {
	*out = *in
	out.OS = in.OS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Image.
func (in *Image) DeepCopy() *Image {
	if in == nil {
		return nil
	}
	out := new(Image)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MobileNetworkIds) DeepCopyInto(out *MobileNetworkIds) {
	*out = *in
	if in.Mncs != nil {
		in, out := &in.Mncs, &out.Mncs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MobileNetworkIds.
func (in *MobileNetworkIds) DeepCopy() *MobileNetworkIds {
	if in == nil {
		return nil
	}
	out := new(MobileNetworkIds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OS) DeepCopyInto(out *OS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OS.
func (in *OS) DeepCopy() *OS {
	if in == nil {
		return nil
	}
	out := new(OS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QoSProfile) DeepCopyInto(out *QoSProfile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QoSProfile.
func (in *QoSProfile) DeepCopy() *QoSProfile {
	if in == nil {
		return nil
	}
	out := new(QoSProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repo) DeepCopyInto(out *Repo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repo.
func (in *Repo) DeepCopy() *Repo {
	if in == nil {
		return nil
	}
	out := new(Repo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
	if in.ServiceCaps != nil {
		in, out := &in.ServiceCaps, &out.ServiceCaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApiRoutingInfo != nil {
		in, out := &in.ApiRoutingInfo, &out.ApiRoutingInfo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpoint) DeepCopyInto(out *ServiceEndpoint) {
	*out = *in
	if in.Ipv4Addresses != nil {
		in, out := &in.Ipv4Addresses, &out.Ipv4Addresses
		*out = make([]IPv4String, len(*in))
		copy(*out, *in)
	}
	if in.Ipv6Addresses != nil {
		in, out := &in.Ipv6Addresses, &out.Ipv6Addresses
		*out = make([]IPv6String, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpoint.
func (in *ServiceEndpoint) DeepCopy() *ServiceEndpoint {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateData) DeepCopyInto(out *UpdateData) {
	*out = *in
	if in.AssocAppPolicies != nil {
		in, out := &in.AssocAppPolicies, &out.AssocAppPolicies
		*out = new(AssocPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.AssocOpsPolicies != nil {
		in, out := &in.AssocOpsPolicies, &out.AssocOpsPolicies
		*out = new(AssocPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateData.
func (in *UpdateData) DeepCopy() *UpdateData {
	if in == nil {
		return nil
	}
	out := new(UpdateData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Zone) DeepCopyInto(out *Zone) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Zone.
func (in *Zone) DeepCopy() *Zone {
	if in == nil {
		return nil
	}
	out := new(Zone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneDetail) DeepCopyInto(out *ZoneDetail) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneDetail.
func (in *ZoneDetail) DeepCopy() *ZoneDetail {
	if in == nil {
		return nil
	}
	out := new(ZoneDetail)
	in.DeepCopyInto(out)
	return out
}
